### ISSUE TITLE
PeakFit line 280-282: SpectralEdge and BandWidth sometimes have (nChannels - 1) values

### ISSUE THREAD

**Issue by shoutman** [NeurophysiologicalBiomarkerToolbox/NBT#110]

**Comment by simon-shlomo** [comment]
this seems to be caused by using a signal which has not been referenced to average reference

**Comment by simon-shlomo** [comment]
hi @shoutman you can re-reference to average reference using
 [Signal, SignalInfo] = nbt_EEGLABwrp(@nbt_ReRef,Signal, SignalInfo, [],0,[]);
should fix the issue
