### ISSUE TITLE
Unit is not correct for absolute power mV^2 instead of \mu V^2

### ISSUE THREAD

**Issue by simon-shlomo** [NeurophysiologicalBiomarkerToolbox/NBT#112]

**Comment by shoutman** [comment]
Which one should it be?

**Comment by simon-shlomo** [comment]
it should be \mu V^2 ie. micro V squared.

**Comment by simon-shlomo** [comment]
seems to be fixed

**Comment by simon-shlomo** [comment]
seems to still be mV^2 using my data..

**Comment by shoutman** [comment]
Could it be that the units are wrong in your analysis files itself?

**Comment by simon-shlomo** [comment]
I just recomputed those files yesterday, so I think it's might be an 
error with the latex

On 04/01/2015 06:02 PM, Simon Houtman wrote:
> Could it be that the units are wrong in your analysis files itself?
>
> On Wed, Apr 1, 2015 at 5:30 PM, Simon-Shlomo Poil 
> <notifications@github.com>
> wrote:
>
> > Reopened #112
> > <https://github.com/NeurophysiologicalBiomarkerToolbox/NBT/issues/112>.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > 
> <https://github.com/NeurophysiologicalBiomarkerToolbox/NBT/issues/112#event-270752605>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/NeurophysiologicalBiomarkerToolbox/NBT/issues/112#issuecomment-88533839>.
>



NBT Analytics
http://www.nbt-analytics.com

IMPORTANT: This message and any attachments are intended for the individual or entity named above. It may contain confidential, proprietary or legally privileged information. No confidentiality or privilege is waived or lost by any mistransmission. If you are not the intended recipient, you must not read, copy, use or disclose this communication to others; also please notify the sender by replying to this message, and then delete it from your system. Thank you.

**Comment by simon-shlomo** [comment]
Works in MacOS
maybe try 
figure;text('Interpreter','Latex',...
'String','$$\mu$$',...
'Position',[.5 .5],...
'FontSize',16)

**Comment by shoutman** [comment]
Should work now

**Comment by simon-shlomo** [comment]
hmm...doesn't work here.. but seems to be a problem with Matlab and the installed fonts..
