### ISSUE TITLE
Confirm that HN tutorials work with new format.

### ISSUE THREAD

**Issue by simon-shlomo** [NeurophysiologicalBiomarkerToolbox/NBT#115]

**Comment by simon-shlomo** [comment]
http://www.nbtwiki.net/doku.php?id=tutorial:load_data#.VRlNO83hl0x : works +1

**Comment by simon-shlomo** [comment]
http://www.nbtwiki.net/doku.php?id=tutorial:visualize_data#.VRlNYs3hl0x :+1:

**Comment by ssimpraga** [comment]
Also verified the upper 2, and also: http://www.nbtwiki.net/doku.php?id=tutorial:clean_data, works.

**Comment by simon-shlomo** [comment]
I added a new milestone for this issues... to collect all issues related to this.

**Comment by ssimpraga** [comment]
works: 

http://www.nbtwiki.net/doku.php?id=tutorial:rejection_of_transient_artifacts#.VSu3PXWUf0p (fixed with 4419b02350f201c8e81f61bcf7f54c2eb9993243)

http://www.nbtwiki.net/doku.php?id=tutorial:how_to_use_ica_to_remove_artifacts#.VSu3XnWUf0o

http://www.nbtwiki.net/doku.php?id=tutorial:re_referencing#.VSu3nHWUf0p

**Comment by ssimpraga** [comment]
http://www.nbtwiki.net/doku.php?id=tutorial:biomarker_computation#.VSu3pHWUf0o works after 58f2a3cb7b8dad7083ba164d1b37e5dbdfbf9311 and 5087bca3edb6865b2aa301a0d752a447485e91b3

**Comment by ssimpraga** [comment]
http://www.nbtwiki.net/doku.php?id=tutorial:test_your_cleaning_tutors#.VSvLRnWUf0o works (5d2b82e6465ce953503392606ebad593208e7099 and 4bde95533b503b31b14dcbee275dbc0db8922779)

**Comment by ssimpraga** [comment]
Error: 
RawSignalInfo.subjectInfo = HN13.S002.20130610.ECR instead of HN13.S002.20130610.ECR_info in the Tutorial Signal downloaded from http://www.nbtwiki.net/doku.php?id=tutorial:rejection_of_transient_artifacts#.VSvZSXWUf0o

**Comment by simon-shlomo** [comment]
I assume this is done also
