### ISSUE TITLE
getData gets stuck in infinite loop when getting data for two groups

### ISSUE THREAD

**Issue by shoutman** [NeurophysiologicalBiomarkerToolbox/NBT#139]

**Comment by shoutman** [comment]
Problem seems to be in createDataObj(). At every iteration (of for-loop on line 49) it eats more memory and after ~20 iterations it crashes.

**Comment by simon-shlomo** [comment]
I am not able to re-produce.. it works fine with the RawDemoset.. What is the exact error message? Or do you have example files?
