### ISSUE TITLE
In nbt_get_artifacts saving an empty Signal!

### ISSUE THREAD

**Issue by ssimpraga** [NeurophysiologicalBiomarkerToolbox/NBT#144]
Line 319 in nbt_get_artifacts:

nbt_SaveSignal([], SignalInfo, Save_dir)

**Comment by ssimpraga** [comment]
That's a fix for nbt_saveSignal but a fix is still needed in nbt_getArtifacts - not passing an empty matrix as the Signal so I'm reopening not to forget that :)

**Comment by simon-shlomo** [comment]
But you don't need to change the Signal in nbt_get_artifacts because all the changes are in the SignalInfo...

**Comment by ssimpraga** [comment]
Ah yes, of course, you're right! ok, then reclosing the issue :)
