### ISSUE TITLE
Error in visualization of nonparametric test results (signed rank and rank sum)

### ISSUE THREAD

**Issue by ssimpraga** [NeurophysiologicalBiomarkerToolbox/NBT#156]
Error in nbt_plot_2conditions_topoAll in line 74. For some reason, it works fine after ttest but not after the non-parametric tests, even though in both cases the chanValuesGroup1 is the same class and contains NaNs :/

**Comment by simon-shlomo** [comment]
And what do you have in the handle?

**Comment by ssimpraga** [comment]
Ah yes, good point, that was it :) At least the first step, there were other errors later but I think it's fixed now!
