### ISSUE TITLE
Speed up computation, change lines in doPhaseLocking

### ISSUE THREAD

**Issue by milecombo** [NeurophysiologicalBiomarkerToolbox/NBT#79]
Hi there,
I am running all biomarkers for 7 freq bands and 256 channels, and I realized that it becomes increasingly slow to store all biomarkers in a structure , up to the point where it's unfeasible.
I know that storing biomarkers in a super-structure it's not the default nbt choice, but it brought up a memory issue that might have escaped.
I stumbled across some things that can be modified.

1) do not store instantaneous phases inside the PLV object. we don't need them, but it's occupying memory of the size of a recoding per frequency band. My analysis file came to weight 7 times more than my original file, and this just slows down the whole thing.
So, comment line 271 
 % PhaseLockingObject.Instphase = Instphase; %  DO NOT STORE PHASE!!

2) I got annoyed by the amount of useless outputs that turned my command line into an essentially uniformative endless stream of channel numbers. This can get some people annoyed, other frustrated, other attempting to throw the monitor down the hallway. Please use progress bars or numbers and avoid disp unless something really new is happening.
http://stackoverflow.com/questions/11050205/text-progress-bar-in-matlab
a dummy example:
>
 reverseStr='';
 for k=1:nchannels
         msg= sprintf( 'chan%3d', k ); 
         fprintf([reverseStr, msg]);  
     reverseStr = repmat(sprintf('\b'), 1, length(msg));
end

**Comment by simon-shlomo** [comment]
assume this is closed?
